// GENERATED by scripts/extract-plant-svgs.mjs — do not edit by hand.
import type { FC } from 'react';
import type { SvgProps } from 'react-native-svg';

type Art = FC<SvgProps>;
export interface FrameArt { back: Art; front: Art; top?: Art; snap?: Art; bugA?: Art; bugB?: Art; puff?: Art }
export interface SpeciesArt { frames: FrameArt[]; paidOff: Art; paidOffBase: Art }

export const SPECIES_ART: Record<1 | 2 | 3 | 4, SpeciesArt> = {
    1: {
        frames: [
            { back: require('../../assets/debt-freedom/plant-1/frame-00-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-1/frame-00.svg').default as Art },
            { back: require('../../assets/debt-freedom/plant-1/frame-01-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-1/frame-01.svg').default as Art },
            { back: require('../../assets/debt-freedom/plant-1/frame-02-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-1/frame-02.svg').default as Art },
            { back: require('../../assets/debt-freedom/plant-1/frame-03-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-1/frame-03.svg').default as Art },
            { back: require('../../assets/debt-freedom/plant-1/frame-04-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-1/frame-04.svg').default as Art },
            { back: require('../../assets/debt-freedom/plant-1/frame-05-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-1/frame-05.svg').default as Art },
            { back: require('../../assets/debt-freedom/plant-1/frame-06-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-1/frame-06.svg').default as Art },
            { back: require('../../assets/debt-freedom/plant-1/frame-07-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-1/frame-07.svg').default as Art },
            { back: require('../../assets/debt-freedom/plant-1/frame-08-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-1/frame-08.svg').default as Art },
            { back: require('../../assets/debt-freedom/plant-1/frame-09-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-1/frame-09.svg').default as Art },
            { back: require('../../assets/debt-freedom/plant-1/frame-10-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-1/frame-10.svg').default as Art },
        ],
        paidOff: require('../../assets/debt-freedom/plant-1/paid-off.svg').default as Art,
        paidOffBase: require('../../assets/debt-freedom/plant-1/paid-off-base.svg').default as Art,
    },
    2: {
        frames: [
            { back: require('../../assets/debt-freedom/plant-2/frame-00-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-2/frame-00.svg').default as Art },
            { back: require('../../assets/debt-freedom/plant-2/frame-01-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-2/frame-01.svg').default as Art },
            { back: require('../../assets/debt-freedom/plant-2/frame-02-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-2/frame-02.svg').default as Art },
            { back: require('../../assets/debt-freedom/plant-2/frame-03-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-2/frame-03.svg').default as Art },
            { back: require('../../assets/debt-freedom/plant-2/frame-04-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-2/frame-04.svg').default as Art },
            { back: require('../../assets/debt-freedom/plant-2/frame-05-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-2/frame-05.svg').default as Art },
            { back: require('../../assets/debt-freedom/plant-2/frame-06-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-2/frame-06.svg').default as Art },
            { back: require('../../assets/debt-freedom/plant-2/frame-07-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-2/frame-07.svg').default as Art },
            { back: require('../../assets/debt-freedom/plant-2/frame-08-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-2/frame-08.svg').default as Art },
            { back: require('../../assets/debt-freedom/plant-2/frame-09-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-2/frame-09.svg').default as Art },
            { back: require('../../assets/debt-freedom/plant-2/frame-10-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-2/frame-10.svg').default as Art },
        ],
        paidOff: require('../../assets/debt-freedom/plant-2/paid-off.svg').default as Art,
        paidOffBase: require('../../assets/debt-freedom/plant-2/paid-off-base.svg').default as Art,
    },
    3: {
        frames: [
            { back: require('../../assets/debt-freedom/plant-3/frame-00-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-3/frame-00.svg').default as Art },
            { back: require('../../assets/debt-freedom/plant-3/frame-01-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-3/frame-01.svg').default as Art },
            { back: require('../../assets/debt-freedom/plant-3/frame-02-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-3/frame-02.svg').default as Art },
            { back: require('../../assets/debt-freedom/plant-3/frame-03-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-3/frame-03.svg').default as Art },
            { back: require('../../assets/debt-freedom/plant-3/frame-04-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-3/frame-04.svg').default as Art },
            { back: require('../../assets/debt-freedom/plant-3/frame-05-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-3/frame-05.svg').default as Art, top: require('../../assets/debt-freedom/plant-3/frame-05-top.svg').default as Art, snap: require('../../assets/debt-freedom/plant-3/frame-05-snap.svg').default as Art, bugA: require('../../assets/debt-freedom/plant-3/frame-05-bug-a.svg').default as Art, bugB: require('../../assets/debt-freedom/plant-3/frame-05-bug-b.svg').default as Art, puff: require('../../assets/debt-freedom/plant-3/frame-05-puff.svg').default as Art },
            { back: require('../../assets/debt-freedom/plant-3/frame-06-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-3/frame-06.svg').default as Art, top: require('../../assets/debt-freedom/plant-3/frame-06-top.svg').default as Art, snap: require('../../assets/debt-freedom/plant-3/frame-06-snap.svg').default as Art, bugA: require('../../assets/debt-freedom/plant-3/frame-06-bug-a.svg').default as Art, bugB: require('../../assets/debt-freedom/plant-3/frame-06-bug-b.svg').default as Art, puff: require('../../assets/debt-freedom/plant-3/frame-06-puff.svg').default as Art },
            { back: require('../../assets/debt-freedom/plant-3/frame-07-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-3/frame-07.svg').default as Art, top: require('../../assets/debt-freedom/plant-3/frame-07-top.svg').default as Art, snap: require('../../assets/debt-freedom/plant-3/frame-07-snap.svg').default as Art, bugA: require('../../assets/debt-freedom/plant-3/frame-07-bug-a.svg').default as Art, bugB: require('../../assets/debt-freedom/plant-3/frame-07-bug-b.svg').default as Art, puff: require('../../assets/debt-freedom/plant-3/frame-07-puff.svg').default as Art },
            { back: require('../../assets/debt-freedom/plant-3/frame-08-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-3/frame-08.svg').default as Art, top: require('../../assets/debt-freedom/plant-3/frame-08-top.svg').default as Art, snap: require('../../assets/debt-freedom/plant-3/frame-08-snap.svg').default as Art, bugA: require('../../assets/debt-freedom/plant-3/frame-08-bug-a.svg').default as Art, bugB: require('../../assets/debt-freedom/plant-3/frame-08-bug-b.svg').default as Art, puff: require('../../assets/debt-freedom/plant-3/frame-08-puff.svg').default as Art },
            { back: require('../../assets/debt-freedom/plant-3/frame-09-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-3/frame-09.svg').default as Art, top: require('../../assets/debt-freedom/plant-3/frame-09-top.svg').default as Art, snap: require('../../assets/debt-freedom/plant-3/frame-09-snap.svg').default as Art, bugA: require('../../assets/debt-freedom/plant-3/frame-09-bug-a.svg').default as Art, bugB: require('../../assets/debt-freedom/plant-3/frame-09-bug-b.svg').default as Art, puff: require('../../assets/debt-freedom/plant-3/frame-09-puff.svg').default as Art },
            { back: require('../../assets/debt-freedom/plant-3/frame-10-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-3/frame-10.svg').default as Art, top: require('../../assets/debt-freedom/plant-3/frame-10-top.svg').default as Art, snap: require('../../assets/debt-freedom/plant-3/frame-10-snap.svg').default as Art, bugA: require('../../assets/debt-freedom/plant-3/frame-10-bug-a.svg').default as Art, bugB: require('../../assets/debt-freedom/plant-3/frame-10-bug-b.svg').default as Art, puff: require('../../assets/debt-freedom/plant-3/frame-10-puff.svg').default as Art },
        ],
        paidOff: require('../../assets/debt-freedom/plant-3/paid-off.svg').default as Art,
        paidOffBase: require('../../assets/debt-freedom/plant-3/paid-off-base.svg').default as Art,
    },
    4: {
        frames: [
            { back: require('../../assets/debt-freedom/plant-4/frame-00-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-4/frame-00.svg').default as Art },
            { back: require('../../assets/debt-freedom/plant-4/frame-01-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-4/frame-01.svg').default as Art },
            { back: require('../../assets/debt-freedom/plant-4/frame-02-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-4/frame-02.svg').default as Art },
            { back: require('../../assets/debt-freedom/plant-4/frame-03-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-4/frame-03.svg').default as Art },
            { back: require('../../assets/debt-freedom/plant-4/frame-04-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-4/frame-04.svg').default as Art },
            { back: require('../../assets/debt-freedom/plant-4/frame-05-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-4/frame-05.svg').default as Art },
            { back: require('../../assets/debt-freedom/plant-4/frame-06-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-4/frame-06.svg').default as Art },
            { back: require('../../assets/debt-freedom/plant-4/frame-07-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-4/frame-07.svg').default as Art },
            { back: require('../../assets/debt-freedom/plant-4/frame-08-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-4/frame-08.svg').default as Art },
            { back: require('../../assets/debt-freedom/plant-4/frame-09-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-4/frame-09.svg').default as Art },
            { back: require('../../assets/debt-freedom/plant-4/frame-10-back.svg').default as Art, front: require('../../assets/debt-freedom/plant-4/frame-10.svg').default as Art },
        ],
        paidOff: require('../../assets/debt-freedom/plant-4/paid-off.svg').default as Art,
        paidOffBase: require('../../assets/debt-freedom/plant-4/paid-off-base.svg').default as Art,
    },
};

export const POT_KIT = {
    emptyPot: require('../../assets/debt-freedom/pot-kit/empty-pot.svg').default as Art,
    soilBall: require('../../assets/debt-freedom/pot-kit/soil-ball.svg').default as Art,
    stake: require('../../assets/debt-freedom/pot-kit/stake.svg').default as Art,
    seed: require('../../assets/debt-freedom/pot-kit/seed.svg').default as Art,
    fragments: [
        require('../../assets/debt-freedom/pot-kit/fragment-01.svg').default as Art,
        require('../../assets/debt-freedom/pot-kit/fragment-02.svg').default as Art,
        require('../../assets/debt-freedom/pot-kit/fragment-03.svg').default as Art,
        require('../../assets/debt-freedom/pot-kit/fragment-04.svg').default as Art,
        require('../../assets/debt-freedom/pot-kit/fragment-05.svg').default as Art,
        require('../../assets/debt-freedom/pot-kit/fragment-06.svg').default as Art,
        require('../../assets/debt-freedom/pot-kit/fragment-07.svg').default as Art,
        require('../../assets/debt-freedom/pot-kit/fragment-08.svg').default as Art,
    ],
};
