// Generated by Supabase (`generate_typescript_types`). Do not edit by hand.
// Regenerate after schema changes. The supabase-js client in `lib/supabase.ts`
// is currently untyped (used only for auth); this file is the canonical schema
// reference and is kept in sync with the remote DB. Latest change: added
// `savings_goals.goal_type` ('saving' | 'debt').
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      expenses: {
        Row: {
          amount: number | null
          category: string | null
          created_at: string
          day: number | null
          id: number
          month: string | null
          sub_category: string | null
          title: string | null
          user_id: string | null
        }
        Insert: {
          amount?: number | null
          category?: string | null
          created_at?: string
          day?: number | null
          id?: number
          month?: string | null
          sub_category?: string | null
          title?: string | null
          user_id?: string | null
        }
        Update: {
          amount?: number | null
          category?: string | null
          created_at?: string
          day?: number | null
          id?: number
          month?: string | null
          sub_category?: string | null
          title?: string | null
          user_id?: string | null
        }
        Relationships: []
      }
      income: {
        Row: {
          amount: number | null
          created_at: string
          day: number | null
          id: number
          jobTitle: string | null
          month: string | null
          source: string | null
          title: string | null
          user_id: string | null
        }
        Insert: {
          amount?: number | null
          created_at?: string
          day?: number | null
          id?: number
          jobTitle?: string | null
          month?: string | null
          source?: string | null
          title?: string | null
          user_id?: string | null
        }
        Update: {
          amount?: number | null
          created_at?: string
          day?: number | null
          id?: number
          jobTitle?: string | null
          month?: string | null
          source?: string | null
          title?: string | null
          user_id?: string | null
        }
        Relationships: []
      }
      lesson_ratings: {
        Row: {
          created_at: string
          id: number
          lesson_id: number
          rating: number
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: number
          lesson_id: number
          rating: number
          user_id: string
        }
        Update: {
          created_at?: string
          id?: number
          lesson_id?: number
          rating?: number
          user_id?: string
        }
        Relationships: []
      }
      savings_goals: {
        Row: {
          completed: boolean | null
          created_at: string | null
          goal_type: string
          id: number
          is_general: boolean
          target_amount: number | null
          target_month: string | null
          target_year: number | null
          title: string
          user_id: string | null
        }
        Insert: {
          completed?: boolean | null
          created_at?: string | null
          goal_type?: string
          id?: number
          is_general?: boolean
          target_amount?: number | null
          target_month?: string | null
          target_year?: number | null
          title: string
          user_id?: string | null
        }
        Update: {
          completed?: boolean | null
          created_at?: string | null
          goal_type?: string
          id?: number
          is_general?: boolean
          target_amount?: number | null
          target_month?: string | null
          target_year?: number | null
          title?: string
          user_id?: string | null
        }
        Relationships: []
      }
      savings_transactions: {
        Row: {
          amount: number
          created_at: string | null
          day: number
          goal_id: number | null
          id: number
          month: string
          source: string
          title: string
          type: string
          user_id: string
        }
        Insert: {
          amount: number
          created_at?: string | null
          day: number
          goal_id?: number | null
          id?: never
          month: string
          source?: string
          title: string
          type: string
          user_id: string
        }
        Update: {
          amount?: number
          created_at?: string | null
          day?: number
          goal_id?: number | null
          id?: never
          month?: string
          source?: string
          title?: string
          type?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "savings_transactions_goal_id_fkey"
            columns: ["goal_id"]
            isOneToOne: false
            referencedRelation: "savings_goals"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
