// Generated by Supabase (`generate_typescript_types`). Do not edit by hand.
// Regenerate after schema changes. The supabase-js client in `lib/supabase.ts`
// is currently untyped (used only for auth); this file is the canonical schema
// reference and is kept in sync with the remote DB. Latest change: added the
// `lesson_series` + `lessons` tables (cloud-hosted video series for the Lessons page).
// NOTE: these two were added by hand to mirror backend/migrations/0001_lesson_series.sql
// because the Supabase MCP was not authenticated when the feature was built — re-run
// `generate_typescript_types` after applying that migration to confirm parity.
// Prior change: added the `month_status` table (per-month open/closed state),
// `savings_goals.is_reconciliation` (auto-managed Reconciliation debt goal flag), and
// `savings_transactions.source` now allows 'rollover' (end-of-month rollover feature).
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      expenses: {
        Row: {
          amount: number | null
          category: string | null
          created_at: string
          day: number | null
          id: number
          month: string | null
          sub_category: string | null
          title: string | null
          user_id: string | null
        }
        Insert: {
          amount?: number | null
          category?: string | null
          created_at?: string
          day?: number | null
          id?: number
          month?: string | null
          sub_category?: string | null
          title?: string | null
          user_id?: string | null
        }
        Update: {
          amount?: number | null
          category?: string | null
          created_at?: string
          day?: number | null
          id?: number
          month?: string | null
          sub_category?: string | null
          title?: string | null
          user_id?: string | null
        }
        Relationships: []
      }
      income: {
        Row: {
          amount: number | null
          budget_type: string
          created_at: string
          day: number | null
          id: number
          jobTitle: string | null
          month: string | null
          source: string | null
          tithe_enabled: boolean
          tithe_rate: number
          title: string | null
          user_id: string | null
        }
        Insert: {
          amount?: number | null
          budget_type?: string
          created_at?: string
          day?: number | null
          id?: number
          jobTitle?: string | null
          month?: string | null
          source?: string | null
          tithe_enabled?: boolean
          tithe_rate?: number
          title?: string | null
          user_id?: string | null
        }
        Update: {
          amount?: number | null
          budget_type?: string
          created_at?: string
          day?: number | null
          id?: number
          jobTitle?: string | null
          month?: string | null
          source?: string | null
          tithe_enabled?: boolean
          tithe_rate?: number
          title?: string | null
          user_id?: string | null
        }
        Relationships: []
      }
      lesson_ratings: {
        Row: {
          created_at: string
          id: number
          lesson_id: number
          rating: number
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: number
          lesson_id: number
          rating: number
          user_id: string
        }
        Update: {
          created_at?: string
          id?: number
          lesson_id?: number
          rating?: number
          user_id?: string
        }
        Relationships: []
      }
      lesson_series: {
        Row: {
          created_at: string
          creator: string | null
          description: string | null
          id: string
          is_premium: boolean
          is_published: boolean
          sort_order: number
          thumbnail_url: string | null
          title: string
        }
        Insert: {
          created_at?: string
          creator?: string | null
          description?: string | null
          id?: string
          is_premium?: boolean
          is_published?: boolean
          sort_order?: number
          thumbnail_url?: string | null
          title: string
        }
        Update: {
          created_at?: string
          creator?: string | null
          description?: string | null
          id?: string
          is_premium?: boolean
          is_published?: boolean
          sort_order?: number
          thumbnail_url?: string | null
          title?: string
        }
        Relationships: []
      }
      lessons: {
        Row: {
          created_at: string
          description: string | null
          duration_seconds: number | null
          id: string
          series_id: string
          sort_order: number
          thumbnail_url: string | null
          title: string
          video_id: string
          video_provider: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          duration_seconds?: number | null
          id?: string
          series_id: string
          sort_order?: number
          thumbnail_url?: string | null
          title: string
          video_id: string
          video_provider?: string
        }
        Update: {
          created_at?: string
          description?: string | null
          duration_seconds?: number | null
          id?: string
          series_id?: string
          sort_order?: number
          thumbnail_url?: string | null
          title?: string
          video_id?: string
          video_provider?: string
        }
        Relationships: [
          {
            foreignKeyName: "lessons_series_id_fkey"
            columns: ["series_id"]
            isOneToOne: false
            referencedRelation: "lesson_series"
            referencedColumns: ["id"]
          },
        ]
      }
      month_status: {
        Row: {
          closed_at: string | null
          month: string
          user_id: string
        }
        Insert: {
          closed_at?: string | null
          month: string
          user_id: string
        }
        Update: {
          closed_at?: string | null
          month?: string
          user_id?: string
        }
        Relationships: []
      }
      savings_goals: {
        Row: {
          completed: boolean | null
          completed_amount: number | null
          completed_at: string | null
          created_at: string | null
          goal_type: string
          id: number
          is_general: boolean
          is_reconciliation: boolean
          target_amount: number | null
          target_month: string | null
          target_year: number | null
          title: string
          user_id: string | null
        }
        Insert: {
          completed?: boolean | null
          completed_amount?: number | null
          completed_at?: string | null
          created_at?: string | null
          goal_type?: string
          id?: number
          is_general?: boolean
          is_reconciliation?: boolean
          target_amount?: number | null
          target_month?: string | null
          target_year?: number | null
          title: string
          user_id?: string | null
        }
        Update: {
          completed?: boolean | null
          completed_amount?: number | null
          completed_at?: string | null
          created_at?: string | null
          goal_type?: string
          id?: number
          is_general?: boolean
          is_reconciliation?: boolean
          target_amount?: number | null
          target_month?: string | null
          target_year?: number | null
          title?: string
          user_id?: string | null
        }
        Relationships: []
      }
      savings_transactions: {
        Row: {
          amount: number
          created_at: string | null
          day: number
          goal_id: number | null
          id: number
          month: string
          source: string
          title: string
          type: string
          user_id: string
        }
        Insert: {
          amount: number
          created_at?: string | null
          day: number
          goal_id?: number | null
          id?: never
          month: string
          source?: string
          title: string
          type: string
          user_id: string
        }
        Update: {
          amount?: number
          created_at?: string | null
          day?: number
          goal_id?: number | null
          id?: never
          month?: string
          source?: string
          title?: string
          type?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "savings_transactions_goal_id_fkey"
            columns: ["goal_id"]
            isOneToOne: false
            referencedRelation: "savings_goals"
            referencedColumns: ["id"]
          },
        ]
      }
      user_settings: {
        Row: {
          budget_type: string
          created_at: string
          firm_foundation_goals_prompted: boolean
          tithe_enabled: boolean
          tithe_rate: number
          updated_at: string
          user_id: string
        }
        Insert: {
          budget_type?: string
          created_at?: string
          firm_foundation_goals_prompted?: boolean
          tithe_enabled?: boolean
          tithe_rate?: number
          updated_at?: string
          user_id: string
        }
        Update: {
          budget_type?: string
          created_at?: string
          firm_foundation_goals_prompted?: boolean
          tithe_enabled?: boolean
          tithe_rate?: number
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
